### ISSUE TITLE
Dataloader для батчинга

### ISSUE THREAD

**Issue by dzlk** [Zhigalov/wsd-cache#1]
У фейсбука есть вот [такая прекрасная штука](https://github.com/facebook/dataloader). Тупая как пробка, но решает свою задачу прекрасно.
Суть в том, чтобы заводить лоадеры данных (читай хоть из базы, хоть из файла, хоть из АПИ), эти лоадеры умеют батчить по ключу одинаковые запросы. Есть возможность делать сложные ключи, указывая функцию для их сериализации. Есть апишка для прогрева кеша лоадера.
Есть минус, что кеш перманентный.

В данный момент я ее трогаю в проекте, могу показать.

Что думаешь?

**Comment by Zhigalov** [comment]
Что-то такое я хотел когда писал слабо связные модули на бекенде блогов. С одной стороны мне не хотелось за один запрос читать одни и те же данные из монги за один запрос пользователя, с другой стороны мне не хотелось таскать эти данные из модуля в модуль (потому что они перестали бы быть слабо связными). Из примеров которые приводят они мне не стало понятно зачем это использовать. Давай посмотрим на твой пример, может он более очевидный.

**Comment by dzlk** [comment]
Обсудили
